project:
  type: website
  output-dir: docs

website:
  title: "Luyueti-Web"
  background: primary
  page-navigation: true
  navbar:
    left:
      - text: "R"
        file: "R/index.qmd"
      - text: "Python"
        file: "python/index.qmd"
      - text: "Quarto"
        file: "quarto/index.qmd"
      - text: "算法"
        file: "算法/index.qmd"
        
  sidebar:
    - title: "R"
      contents: 
        - R/index.qmd
    
    - title: "Python"
      contents: 
        - python/index.qmd
        
    - title: "Quarto"
      contents: 
        - quarto/index.qmd
        - section: "20220906"
          contents: 
            - quarto/Presentation.qmd
        - section: "20220905"
          contents: 
            - quarto/tabset_group.qmd
    
    - title: "算法"
      contents: 
        - 算法/index.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-tools:
      source: true
      toggle: true
      caption: none
    smooth-scroll: true
    code-fold: true

editor: visual

