project:
  type: website
  output-dir: docs

website:
  title: "Luyueti-Web"
  background: primary
  navbar:
    left:
      - text: "R"
        file: "R/index.qmd"
      - text: "Python"
        file: "python/about.qmd"
      - text: "Quarto"
        file: "quarto/index.qmd"
        
  sidebar:
    - title: "R"
      contents: 
        - R/index.qmd
    
    - title: "Python"
      contents: 
        - python/about.qmd
        
    - title: "Quarto"
      contents: 
        - quarto/index.qmd
        
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

