---
title: "mlr3"
format: 
  html:
    number-sections: true
    toc-depth: 5
---

```{r}
#| echo: false
#| warning: false
#| message: false
library(tidyverse)
```
## TASKS

### 导入数据 

```{r}
data("mtcars", package = "datasets")
mtcars %>% head() %>% knitr::kable()
```

### 建立TASK

```{r}
library("mlr3")

task_mtcars = as_task_regr(mtcars, target = "mpg", id = "cars")
print(task_mtcars)
```
### 快速绘图

```{r}
library("mlr3viz")
autoplot(task_mtcars, type = "pairs")
```

### Task API

#### 数据的基本信息

TASK中数据的行数与列数
```{r}
task_mtcars$nrow
task_mtcars$ncol
task_mtcars$feature_names
task_mtcars$target_names
```

#### 对TASK中数据的修改

数据规模缩小
```{r}
task_mtcars$select(c("am", "carb", "wt")) # 只能选feature
task_mtcars$filter(2:4) # 仅支持输入row id
task_mtcars$data() %>% knitr::kable()
```

数据规模扩大
```{r}
task_mtcars$rbind(
  data.frame(mpg=1, am=1, carb=1, wt=1)
  # df必须和原始数据格式一样， 必须有所有的变量
)
task_mtcars$data() %>% knitr::kable()
```

## Learner

```{r}
learner = lrn("classif.rpart")
learner
```

### Learner参数

```{r}
learner$param_set
```

直接在初始化时设定参数
```{r}
learner = lrn("classif.rpart", id = "rp", cp = 0.001)
learner$id
```

## 训练和预测

```{r}
task = tsk("pima")
learner = lrn("classif.rpart")
task$data() %>% head() %>% knitr::kable()
```

### 训练

训练的模型保存在`learner$model`中
```{r}
learner$model
```

训练模型
```{r}
learner$train(task)
learner$model
```

### 预测
```{r}
prediction = learner$predict_newdata(task$data())
as.data.table(prediction) %>% head() %>% knitr::kable()
```

### 测试集训练集

```{r}
set.seed(7)
train_set = sample(task$row_ids, 0.67 * task$nrow)
test_set = setdiff(task$row_ids, train_set)
# train on the training set
learner$train(task, row_ids = train_set)

# predict on the test set
prediction = learner$predict(task, row_ids = test_set)

# the prediction naturally knows about the "truth" from the task
prediction
```

### 训练效果评估

所有的评估方法
```{r}
mlr_measures
```

设定评估角度为acc
```{r}
measure = msr("classif.acc")
measure
```

```{r}
prediction$score(measure)
```

设置多个评估标准
```{r}
measures = msrs(c("classif.tpr", "classif.tnr"))
prediction$score(measures)
```

## 调参

### ROC曲线和阈值

```{r}
task = tsk("sonar")
learner = lrn("classif.rpart", predict_type = "prob")
task
```
#### 划分训练集测试集

```{r}
# split into training and test
splits = partition(task, ratio = 0.8)
str(splits)
```

链式训练
```{r}
pred = learner$train(task, splits$train)$predict(task, splits$test)
pred$confusion
```

### Resampling

```{r}
task = tsk("penguins")
learner = lrn("classif.rpart")
```

Resample Method列表
```{r}
as.data.table(mlr_resamplings)
```

#### 初始化

```{r}
resampling = rsmp("holdout")
print(resampling)
```

两种方法设置holdout比例
```{r}
resampling$param_set$values = list(ratio = 0.8)
resampling = rsmp("holdout", ratio=0.8)
resampling$param_set$values$ratio
```

#### 应用method

```{r}
resampling$instantiate(task)
train = resampling$train_set(1)
test = resampling$test_set(1)
str(train)
```

#### 执行
```{r}
task = tsk("penguins")
learner = lrn("classif.rpart", maxdepth = 3, predict_type = "prob")
resampling = rsmp("cv", folds = 3)

rr = resample(task, learner, resampling, store_models = TRUE)
print(rr)
```
效果评估，所有fold中scroe的均值
```{r}
rr$aggregate(msr("classif.ce"))
```

获取每个模型训练的结果
```{r}
lrn = rr$learners[[1]]
lrn$model
```

获取在验证集上训练的结果
```{r}
rr$prediction() %>% 
  as.data.table() %>% 
  arrange(row_ids) %>%
  head() %>%
  knitr::kable()
```

### Benchmarking

```{r}
library("mlr3verse")

design = benchmark_grid(
  tasks = tsks(c("spam", "german_credit", "sonar")),
  learners = lrns(c("classif.ranger", "classif.rpart", "classif.featureless"),
    predict_type = "prob", predict_sets = c("train", "test")),
  resamplings = rsmps("cv", folds = 3)
)
as.data.table(design) %>% head() %>% knitr::kable()
```


















